// Texto padrão da Convenção de Condomínio do escritório — portado verbatim de cota_saas
// (lib/documentos/convencaoArtigos.ts). Itens que começam com "CAPÍTULO" viram título de
// seção no documento; os demais viram parágrafo.
export const CONVENCAO_ARTIGOS: string[] = [
  'CAPÍTULO II - DAS PARTES COMUNS',
  'ART. 2º - São partes de propriedade comum, inalienáveis e indivisíveis aquelas a que se refere o artigo 1.331 § 2º do Código Civil e, muito especialmente, o terreno, fundações, estruturas e coberturas; as escadas, o transformador e quadro disjuntores; as calhas condutoras de água pluviais, os dutos de distribuição de água e esgoto; as linhas de distribuição de energia elétrica, telefonia, intercomunicação e sinal de TV/Satélite, as calçadas, bem como os bens posteriormente agregados ao patrimônio comum. Todos com seus respectivos equipamentos, móveis, utensílios e acessórios.',
  'CAPÍTULO III – DAS PARTES AUTÔNOMAS',
  'ART 3º - Constitui propriedade exclusiva do condômino a unidade autônoma, indicada pela numeração própria, com as correspondentes frações ideais do terreno.',
  'CAPÍTULO IV - DA DIREÇÃO',
  'ART. 4º. - A Direção do Edifício será exercida:',
  'a)      pela Assembléia Geral;',
  'b)      pelo Síndico, e/ou subsíndico nos termos da presente Convenção;',
  '§ Único - Será eleito o Síndico que será o representante legal e o subsíndico;',
  'CAPÍTULO V - DA ASSEMBLEIA GERAL',
  'ART 5º - As Assembleias serão convocadas mediante carta registrada ou protocolada pelo síndico aos condôminos que representem pelo menos um quarto do condomínio, com antecedência mínima de 10 (dez) dias e realizar-se-ão no próprio Edifício.',
  'ART 6º – As convocações das Assembleias Gerais Ordinárias, serão acompanhadas do orçamento relativo ao ano seguinte.',
  'ART 7º – As Assembleias Gerais Extraordinárias poderão ser convocadas em prazo inferior ao estabelecido no artigo 7º, quando comprovada sua urgência.',
  'ART 8º – É lícito na mesma notificação fixar horário em que se realizará a Assembléia em primeira e segunda convocação, desde que estabelecido entre uma e outra o prazo de 30 (trinta) minutos.',
  'ART 9º – As Assembleias serão presididas pelo síndico, subsíndico ou condômino, o qual poderá nomear secretário para lavrar a ata, que deverá ser assinada por todos os presentes.',
  'ART 10º – Cada condômino terá direito a um voto por cada unidade de apartamento que possuir.',
  'ART 11º – Se a unidade pertencer a mais de uma pessoa, estas elegerão um deles para representa-la perante à Assembleia, credenciando-o por escrito.',
  'ART 12º – Não participará das Assembleias o condômino que estiver em atraso com as suas contribuições ou em débito com multas que lhe forem impostas.',
  'Parágrafo único: Para participar o condômino deverá efetuar o pagamento até 48 (quarenta e oito) horas antes da realização da mesma.',
  'ART 13º – O Condômino poderá fazer-se representar por procurador com poderes específicos, através de instrumento público ou particular, seja o representante condômino ou não.',
  'ART 14º - Será exigida maioria qualificada de votos nos casos previstos em lei, ou por esta Convenção, e nas demais maioria simples.',
  'ART 15º – É vedado ao Condômino votar sobre assuntos em que tenha interesse particular.',
  'ART 16º – A Assembleia Geral Ordinária realizar-se-á, no mês de Janeiro, para discutir e votar o relatório da administração, relativamente ao ano findo, discutir e votar o orçamento das despesas e receitas, fixando quota de reserva se convier, eleger o Síndico e o subsíndico quando for o caso, votar as demais matérias constantes da ordem do dia.',
  'ART 17º – A Assembleia realizar-se-á em primeira convocação com 50% (cinqüenta por cento) dos condôminos e, em segunda com qualquer número.',
  'ART 18º – Compete as Assembleias Gerais Extraordinárias deliberar sobre matéria de interesse geral do Condomínio, não podendo discutir sobre o direito de propriedade ou pessoal de cada Condômino: decidir sobre ou em grau de recurso, assuntos que tenham sido deliberados pelo Síndico e a elas legados a pedido do interessado; apreciar as demais matérias constantes da ordem do dia; examinar os assuntos que lhe sejam propostos por qualquer Condômino; discutir e apreciar a destituição de Síndico, após parecer da assembleia geral, desde que baseados as provas concretas que impossibilitem ao mesmo continuar no cargo.',
  'ART 19º – Serão exigidos 2/3 (dois terços) de votos para os seguintes casos: alteração da Convenção do Condomínio no todo ou em parte; alteração ou modificação da estrutura do prédio; discutir e deliberar sobre a venda de parte comuns ou ceder o dinheiro à ela reservados; outras matérias estipuladas em lei e na presente Convenção.',
  'ART 20º – Serão exigidos 2/3 (dois terços), nos seguintes casos: em matéria que importe na realização ou modificação de benfeitorias úteis; discutir e deliberar sobre a reedificação ou não em caso de incêndio ou sinistro que destrua totalmente o prédio; destituição de membros do Conselho Fiscal; discutir ou deliberar sobre o ingresso de qualquer ação judicial, salvo as especialmente previstas nesta Convenção nos demais casos previstos em lei e na presente convenção.',
  'ART 21º – As deliberações das Assembleias, desde que cumpridas as formalidades para instalação e convocação, serão obrigatórias à todos os Condôminos, independente de comparecimento ou voto, cumprindo ao Síndico executa-las e cumpri-las fielmente.',
  'ART 22º - As Assembleias Gerais terão os resultados das deliberações lavradas em ata, no livro próprio, assinado pelo Presidente e Secretário, e demais condôminos, e será feito um extrato para distribuição a todos os condôminos para sua ciência.',
  'Parágrafo único: As assinaturas dos condôminos dissidentes poderão constar em ata, sendo que a mesma supre a falta de convocação.',
  'ART 23º – Não irá ser constituído fundo de reserva, pois mês a mês há o rateio para pagamento das despesas fixas e variáveis.',
  'CAPÍTULO VI - DA ADMINISTRAÇÃO DO CONDOMÍNIO',
  'ART 24º - A Administração do Condomínio será exercida pelo Síndico, devendo o encargo ser exercido por um dos condôminos, nos termos da legislação vigente desta Convenção e do Regimento Interno.',
  '§ 1º - O Síndico será eleito em Assembleia Geral, por maioria de votos dos presentes, para mandato de 02 (dois) anos, podendo ser reeleitos.',
  '§ 2º - O Síndico terá isenção da taxa de condomínio, pois se trata de uma atividade remunerada, cuja remuneração é a isenção da cota condominial ordinária, exceto na condição de taxa extra quando deverá participar do pagamento igualmente aos outros condôminos.',
  '§ 3º - A isenção da taxa condominial a que se refere o parágrafo anterior, em hipótese alguma gera relação de emprego entre o Síndico e o Condomínio.',
  '§ 4º – Em caso de impedimento, morte ou ausência do síndico, será convocada imediatamente a Assembléia Geral Extraordinária para eleição de novo Síndico;',
  'ART 25º - Compete ao Síndico:',
  'a)      representar ativa e passivamente o Condomínio em juízo ou fora dele, e praticar atos de defesa dos interesses comuns, nos limites das atribuições conferidas por esta Convenção e pela Lei vigente.',
  'b)      exercer a administração interna do edifício no que diz respeito a sua vigilância, moralidade e segurança, bem como os serviços que interessem a todos os moradores.',
  'c)       praticar os atos atribuídos pelas Leis, por esta Convenção e pelo Regimento Interno.',
  'd)      impor as multas estabelecidas na Lei e no Regimento Interno.',
  'e)      cumprir e fazer cumprir a Convenção e o Regimento Interno, bem como executar as deliberações das assembléias.',
  'f)        prestar contas à Assembleia dos Condôminos.',
  'g)      contratar prestadores de serviço para o Condomínio e/ou efetuar contratos de locação de serviços de firma especializada.',
  'i)        ordenar reparos e adquirir o que for necessário à segurança e conservação do Edifício, até o limite do orçamento previsto no exercício.',
  'j)        cobrar taxas relativas às despesas comuns e as multas estabelecidas no Regimento Interno.',
  'k)       manter um controle de Caixa que será mensalmente apresentado ao Conselho Consultivo.',
  'l)        prestar, quando solicitado, quaisquer informações sobre os atos de Administração e sobre as contas de sua gestão.',
  'm)    convocar Assembleias Gerais Ordinárias e Extraordinárias, estas quando julgar conveniente ou quando requeridas por, no mínimo, 1/4 (um quarto) dos Condôminos.',
  'n)      abrir e encerrar o livro de atas e o livro de presença, rubricar as respectivas folhas, conservá-los sempre à sua guarda e responsabilidade, bem como fornecer aos Condôminos, quando solicitado, cópias autenticadas das atas das Assembléias ou de anotações do livro de presença.',
  'p)      dar ciência imediata à Assembléia, das citações que receber.',
  'q)      constituir Advogados para o Condomínio em pleitos judiciais e controlar os respectivos honorários dentro da verba orçamentária para tal fim.',
  'r)       apresentar proposta orçamentária da receita e da despesa para o exercício econômico-financeiro seguinte.',
  's)       manter guardada toda a documentação relativa ao Condomínio, para eventuais verificações contábeis, durante o prazo de 05 (cinco) anos (lei n. 6434 de 15 de julho de 1977).',
  't)        verificar possibilidade de realizar contratação do seguro da edificação.',
  '§ Único - O Síndico pode transferir a outrem, total ou parcialmente, os poderes de representação ou as funções administrativas, mediante aprovação da Assembleia.',
  'ART 26º - No final de cada exercício, o Síndico apresentará à Assembleia Geral Ordinária, as contas de sua administração, exibindo a documentação respectiva.',
  'ART 27º - O Síndico entregará ao seu sucessor, mediante recibo, todos os bens, valores, livros e demais documentos do Condomínio.',
  'CAPÍTULO VII - DOS DIREITOS E DEVERES DOS CONDÔMINOS',
  'ART 28º – São direitos dos condôminos',
  'a)      usar, gozar e dispor da respectiva unidade autônoma de acordo com seu destino, desde que não prejudique a segurança e solidez do Edifício, não causem danos ou incômodos aos demais moradores, que não infrinjam as normas legais, das disposições desta Convenção e do Regimento Interno.',
  'b)      usar, gozar das partes do Edifício, desde que não impeçam ou perturbem idêntico uso e gozo pelos demais moradores com as mesmas restrições da alínea anterior.',
  'c)       manter em seu poder as chaves das portas de ingresso do Edifício.',
  'd)      examinar em qualquer tempo os livros e arquivos da Administração e pedir esclarecimentos ao Síndico.',
  'e)      comparecer às Assembleias Gerais e, quando quites com a contribuição, nelas discutir, votar e ser votado.',
  'f)        denunciar ao Síndico qualquer irregularidade que observarem.',
  'g)      convocar Assembleias Gerais Extraordinárias, na forma prevista no Art. 10º desta Convenção, e nela recorrer dos atos do Síndico, que julgarem prejudiciais ao interesse comum.',
  'h)      exercer as funções de Síndico e subsíndico.',
  'i)        apresentar propostas, ou opinar sobre os assuntos de interesse geral do Condomínio, sobretudo no que se refere à aquisição de bens ou contratação de serviços para o Condomínio.',
  '§ Único - A renúncia de qualquer Condômino aos seus direitos, em caso algum, valerá como escusa de exonerá-lo de seus deveres.',
  'Art. 29º - São deveres de cada Condômino:',
  'a)      Além daqueles constantes na Lei 4591 de 16 de dezembro de 1964 e no Código Civil:',
  'b)      não alterar a forma externa da fachada ou das áreas internas de uso comum.',
  'c)       não modificar a distribuição interna dos cômodos do Apartamento, sem consentimento prévio do Síndico e autorização por escrito deste, referendada pelo Agente Financeiro.',
  'd)      não destinar a unidade à utilização diversa de sua finalidade, e nem usá-la de forma indecorosa, nociva e perigosa aos demais Condôminos e moradores, ou que lhe causem danos ou incômodos.',
  'e)      observar e cumprir o Regimento Interno e a Convenção.',
  'f)        o Condômino ou infrator dos deveres estipulados na alínea anterior deste artigo, ficará sujeito ao pagamento de multas que serão discriminadas no Regimento Interno.',
  'g)      o Condômino que vender ou alugar o respectivo apartamento, deverá dar ciência ao comprador ou locatário, das instruções constantes nesta Convenção.',
  'h)      não usar as respectivas unidades, nem alugá-las para atividades ruidosas ou a pessoas de maus costumes.',
  'i)        não lançar quaisquer detritos, objetos ou líquidos para o exterior das unidades.',
  'j)        não decorar as paredes, portas, esquadrias com cores ou tonalidades diversas das empregadas no Edifício.',
  'k)      não permitir que sejam impedidas as partes comuns do Edifício, com a colocação nelas, de objetos de qualquer natureza.',
  'l)        contribuir para as despesas comuns do edifício, custeio de obras e outras despesas determinadas pela Assembléia Geral em cotas proporcionais e efetuando os pagamentos nos prazos estabelecidos.',
  'm)    contribuir para o custeio de outras despesas extraordinárias, autorizadas pela Assembléia Geral, na forma por que for estabelecida e na proporção das respectivas frações.',
  'n)      permitir o ingresso do Síndico ou preposto deste em sua unidade, quando isto se torne indispensável à inspeção ou realização de trabalhos relativos à estrutura geral do Edifício, ou necessário à efetuação de serviços ou reparos em tubulações da própria unidade autônoma ou da vizinhança.',
  'o)      comunicar imediatamente ao Síndico a ocorrência de moléstia contagiosa em sua unidade.',
  'p)      apresentar ao síndico, sempre que solicitado ou quando houver mudança, a documentação da propriedade e posse da unidade autônoma.',
  'q)      evitar a sobrecarga da estrutura e lajes do edifício com peso superior a 150 kg/m2, ou ainda as instalações elétricas, hidráulicas, telefônicas, de intercomunicação e sinal de televisão de sua unidade autônoma, com o uso indevido de equipamentos não dimensionados em projeto, de maneira que possa comprometer a segurança ou o perfeito funcionamento das coisas, utilidades ou serviços comuns.',
  'Art. 30º – As reparações e manutenções das instalações de água e de energia elétrica de cada unidade autônoma serão de responsabilidade do respectivo proprietário, até o ponto de ligação com a tubulação ou rede tronco principal do condomínio.',
  'ART. 31º - Nos casos de infiltração verificada nas paredes, tetos ou assoalhos do edifício, proveniente de águas oriundas das colunas gerais do Edifício, a responsabilidade do Condomínio nas reparações dos danos causados circunscreve-se ao conserto ou substituições das canalizações pertencentes ao Condomínio e à reparação das partes afetadas (tetos, paredes ou assoalhos) com acabamento idêntico ao constante nas especificações iniciais de construção do prédio. Quando as partes atingidas tenham sofrido pintura ou qualquer outro tipo de revestimento especial fora daquelas especificadas, sua restauração ficará a cargo do Proprietário do apartamento danificado.',
  '§ 1º - Quando se verificarem infiltrações provenientes de outra unidade, em banheiros, cozinhas, tanques de lavar roupas, etc., cabe ao Proprietário deste último mandar eliminar imediatamente e reparar os danos causados ao outro Apartamento. Não havendo resolução do problema pelo morador ou proprietário, deverá o síndico intermediar o conflito e tomar as medidas cabíveis, tais como aplicação de advertência escrita e multa.',
  '§ 2º - Os danos causados à área comum serão cobrados unicamente do infrator. No caso de autoria desconhecida, será a despesa rateada entre os moradores da área atingida.',
  'ART. 32º Instalar as condensadoras de ar condicionado nos locais já indicados com suas respectivas caixas, não podendo fazer instalações em outros locais da fachada.',
  'CAPÍTULO VIII - DAS CONTRIBUIÇÕES PARA DESPESAS',
  'ART. 33º – Constituem encargos comuns do Condomínio, a serem suportados pelos condôminos, as despesas necessárias à conservação, manutenção, limpeza, segurança e funcionamento das áreas e instalações de uso comum, bem como os tributos, tarifas, seguros, serviços e demais encargos que incidam sobre o Condomínio ou sejam de interesse comum das unidades autônomas.',
  'ART. 34º – O rateio das contribuições ordinárias será realizado na proporção das respectivas frações ideais de cada unidade autônoma, salvo disposição legal ou deliberação regularmente aprovada em sentido diverso.',
  'ART 35º – Na mesma proporção serão rateadas as despesas extraordinárias.',
  'ART 36º – No caso da existência de déficit, o mesmo será rateado entre os condôminos na proporção estabelecida no artigo 34º, e será arrecadado no prazo de 30 (trinta) dias.',
  'ART 37º – O condômino responderá pessoalmente pelas despesas a que der causa, nas partes comuns, bem como nas unidades autônomas.',
  'ART 38º - O saldo remanescente de cada exercício será incorporado ao seguinte, se outro destino não lhe for dado pela Assembléia, desde que em favor do Condomínio.',
  'ART 39º – O síndico poderá emitir boletos correspondentes as contribuições e rateios mensais do condomínio, com vencimento até dia 05 ou 10 de cada mês, podendo usar se quiser a rede bancária para cobrança.',
  'ART 40º – Nenhum pavimento fica isento de participar dos rateios e chamadas extras, provocadas por reformas, melhorias e demais casos.',
  'ART 41º – Caso o edifício esteja segurado contra incêndio ou qualquer risco que possa destruir total ou parcialmente o prédio é lícito aos condôminos aumentar o seguro de sua unidade ou de benfeitorias por ele introduzidas.',
  'ART 42º – Na ocorrência de sinistro total ou que destrua mais de dois terços do prédio a Assembleia Geral reunir-se-á para indicar uma comissão de três (3) condôminos, no prazo de quinze dias, investidos de poderes para receber a indenização e deposita-la em nome do condomínio, em estabelecimento bancário, abrir concorrência para a reconstrução, após determinação da Assembleia; acompanhar os trabalhos dos construtores e repartições públicas. Este dispositivo se aplica somente se houver contratação do seguro da edificação estabelecida no artigo 25, letra "t".',
  'ART 43º – Não sendo suficiente a indenização, concorrerão os demais condôminos para o pagamento do excesso na proporção de suas frações ideais, salvo deliberação contrária da maioria. Este dispositivo se aplica somente se houver contratação do seguro da edificação estabelecida no artigo 25, letra "t".',
  'ART 44º – Poderá ser deliberada a venda do terreno e do que sobrar do prédio, partilhando-se os valores de venda e seguro, por maioria qualificada na Assembleia.',
  'ART 45º - As unidades que estiverem fechadas serão cobradas e arcarão da mesma forma com suas obrigações;',
];

// Só entra na Convenção quando o trabalho está marcado "condomínio com duas unidades" —
// a governança padrão acima pressupõe vários votantes, o que não funciona entre só 2 condôminos.
export const CONVENCAO_DUAS_UNIDADES: string[] = [
  'CAPÍTULO IX - DAS REGRAS ESPECÍFICAS PARA CONDOMÍNIO COM DUAS UNIDADES AUTÔNOMAS',
  'ART. 46º – Sendo o condomínio constituído por apenas 2 (duas) unidades autônomas, os condôminos deverão buscar, prioritariamente, a solução consensual das matérias de interesse comum, antes de qualquer medida unilateral.',
  'ART. 47º – Nas deliberações que, por lei ou por esta Convenção, exijam quórum qualificado (maioria qualificada ou 2/3 dos votos), a manifestação favorável de apenas um dos condôminos não é suficiente para a aprovação, sendo necessária a concordância de ambos, dada a impossibilidade de fracionamento do quórum entre apenas 2 (dois) votantes.',
  'ART. 48º – Havendo divergência ou empate entre os condôminos sobre matéria sujeita à deliberação por maioria simples, observar-se-á o seguinte procedimento: I – nova tentativa de deliberação, mediante convocação específica, no prazo de 15 (quinze) dias; II – persistindo a divergência, os condôminos buscarão solução consensual ou, se necessário, mediação extrajudicial; III – as obras e providências necessárias e urgentes à segurança, conservação ou preservação do imóvel poderão ser realizadas independentemente de consenso prévio, devendo o condômino que as determinar comunicar imediatamente o outro e apresentar, a posteriori, a justificativa e os comprovantes das despesas, que serão rateadas na forma desta Convenção.',
  'Parágrafo único – Nenhum condômino poderá valer-se de eventual divergência ou empate para impedir, de forma indefinida, a realização de providência legalmente obrigatória ou necessária à conservação e segurança do condomínio.',
];
